version: "{branch}-{build}"
test: off

os:
  - Visual Studio 2015

platform:
#  - x86
  - x64

configuration:
#  - Debug
#  - Release
  - RelWithDebInfo

install:
  - cinst graphviz.portable

init:
  - if %platform%==x64 (set generator=Visual Studio 14 2015 Win64) else (set generator=Visual Studio 14 2015)
  - if %platform%==x64 (set msplatform=x64) else (set msplatform=Win32)

before_build:
  - md build
  - cd build

build_script:
  - echo "Platform      = %platform%"
  - echo "MS Platform   = %msplatform%"
  - echo "Configuration = %configuration%"
  - echo "Generator     = %generator%"
  - git submodule update --init --recursive
  - appveyor DownloadFile https://github.com/comphack/external/releases/download/external-18/external-0.1.1-win64.zip -FileName external.zip
  - 7z x external.zip
  - del external.zip
  - mv external* ..\binaries
  - appveyor DownloadFile http://doxygen.nl/files/doxygen-1.8.14.windows.x64.bin.zip -FileName doxygen.zip
  - mkdir doxygen
  - cd doxygen
  - 7z x ..\doxygen.zip
  - cd ..
  - del doxygen.zip
  - set PATH=%APPVEYOR_BUILD_FOLDER%\build\doxygen;%PATH%
  - cmake -DGENERATE_DOCUMENTATION=OFF -DCMAKE_INSTALL_PREFIX="%appveyor_build_folder%\build\install" -DCMAKE_CUSTOM_CONFIGURATION_TYPES="%configuration%" -G"%generator%" ..
  - cmake --build . --config %configuration% --target package

artifacts:
  - path: build\objgen-*.msi
    name: objgen_installer
  - path: build\objgen-*.zip
    name: objgen_archive
